testdayo/config/routes.rb
Testdayo::Application.routes.draw do
  resources :twitters

end

testdayo/app/models/twitter.rb
class Twitter < ActiveRecord::Base
  attr_accessible :tweet
end

testdayo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

testdayo/app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  # GET /twitters
  # GET /twitters.json
  def index
    @twitters = Twitter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @twitters }
    end
  end

  # GET /twitters/1
  # GET /twitters/1.json
  def show
    @twitter = Twitter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @twitter }
    end
  end

  # GET /twitters/new
  # GET /twitters/new.json
  def new
    @twitter = Twitter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @twitter }
    end
  end

  # GET /twitters/1/edit
  def edit
    @twitter = Twitter.find(params[:id])
  end

  # POST /twitters
  # POST /twitters.json
  def create
    @twitter = Twitter.new(params[:twitter])

    respond_to do |format|
      if @twitter.save
        format.html { redirect_to @twitter, notice: 'Twitter was successfully created.' }
        format.json { render json: @twitter, status: :created, location: @twitter }
      else
        format.html { render action: "new" }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /twitters/1
  # PUT /twitters/1.json
  def update
    @twitter = Twitter.find(params[:id])

    respond_to do |format|
      if @twitter.update_attributes(params[:twitter])
        format.html { redirect_to @twitter, notice: 'Twitter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitters/1
  # DELETE /twitters/1.json
  def destroy
    @twitter = Twitter.find(params[:id])
    @twitter.destroy

    respond_to do |format|
      format.html { redirect_to twitters_url }
      format.json { head :no_content }
    end
  end
end

testdayo/app/helpers/application_helper.rb
module ApplicationHelper
end

testdayo/app/helpers/twitters_helper.rb
module TwittersHelper
end

testdayo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testdayo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

testdayo/app/views/twitters/_form.html.erb
<%= form_for(@twitter) do |f| %>
  <% if @twitter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twitter.errors.count, "error") %> prohibited this twitter from being saved:</h2>

      <ul>
      <% @twitter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet %><br />
    <%= f.text_field :tweet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

testdayo/app/views/twitters/edit.html.erb
<h1>Editing twitter</h1>

<%= render 'form' %>

<%= link_to 'Show', @twitter %> |
<%= link_to 'Back', twitters_path %>

testdayo/app/views/twitters/index.html.erb
<h1>Listing twitters</h1>

<table>
  <tr>
    <th>Tweet</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @twitters.each do |twitter| %>
  <tr>
    <td><%= twitter.tweet %></td>
    <td><%= link_to 'Show', twitter %></td>
    <td><%= link_to 'Edit', edit_twitter_path(twitter) %></td>
    <td><%= link_to 'Destroy', twitter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Twitter', new_twitter_path %>

testdayo/app/views/twitters/new.html.erb
<h1>New twitter</h1>

<%= render 'form' %>

<%= link_to 'Back', twitters_path %>

testdayo/app/views/twitters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tweet:</b>
  <%= @twitter.tweet %>
</p>


<%= link_to 'Edit', edit_twitter_path(@twitter) %> |
<%= link_to 'Back', twitters_path %>